version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
